  Introduction : 'Train INN'
  optim : "ours"    #optim method
  cost_fn : "sim_cmpr0"   #the type of loss function 
  indices : "def"      #decide which part of gradients to be involved in the final gradients match loss.
  weights : 'equal'    #weight of every graident scalar's matching loss
  init : 'randn'     #how we initial the original latent code.
  model : "ResNet18"   #FL model
  restarts : 1

  num_images : 4   #How many images we want to reconstruct at a batch
  num_exp : 200
  # num_exp : 1
  target_id : 0
  lr : 0.03
  total_variation : 0.0001     #the coefficient of total variation
  bn_stat : 0       #choose if we use bn statistic to regularizer
  image_norm : 0.000001    #the coefficient of norm regularizer
  group_lazy : 0    #choose if we use group lazy regularization
  z_loss : 0

  max_iterations : 1000 #1000    #Maximum number of iterations for reconstruction.



  #For output data
  exp_name : 'train_inn_0.0005'   #Same latent space search
  inn_path : None
  output_dir : 'models/stylegan2/'

  #params for algorithm choice
  prompt_gen : true
  inter_optim : false
  gias : false
  ggl : false

  # The pre-trained StyleGAN checkpoint
  generative_model : 'stylegan2_io'
  gen_dataset : 'FFHQ64'
  dataset : "FFHQ64"
  data_path : "./dataset/FFHQ-128"
  ckpt: './inversefed/genmodels/stylegan2_io/stylegan2-ffhq-config-f.pt'
  # ckpt: '/home/itml_fh/gradient-inversion-generative-image-prior/inversefed/genmodels/stylegan2_io/imagenet.pt'


  #For prompt
  prompt: True
  prompt_lr : 0.0005
  prompt_iteration : 500
  meta_lr : 0.01
  inn_path : ''
  #cmd instruction
  # python train_inn.py 
  